Repository r-dbi/DBI, pull requests merged in 2023-12, with the labels that each got.

#430 docs: Clarify repeated parameter binding
  R/dbBind.R
  man/dbBind.Rd
  man/dbClearResult.Rd
  man/dbColumnInfo.Rd
  man/dbFetch.Rd
  man/dbGetRowsAffected.Rd
  man/dbHasCompleted.Rd
  man/dbSendQuery.Rd
  man/dbSendStatement.Rd
Labels: mergequeue

#431 test: Run DBItest for SQLite as part of the checks here
  .Rbuildignore
  tests/testthat/helper-dev.R
  tests/testthat/test-DBItest.R
Labels: mergequeue-priority, mergequeue

#432 chore: Test with dev version of DBItest
  DESCRIPTION
Labels: mergequeue

#433 chore: Rename files
  R/14-dbSendQuery.R
  R/15-dbBind.R
  R/24-dbSendQueryArrow.R
  man/dbBind.Rd
  man/dbSendQuery.Rd
Labels: mergequeue-priority, mergequeue

#434 feat: Better default `dbFetchArrow()` regarding corner cases and schema inference
  R/dbFetchArrow_DBIResultArrow.R
Labels: mergequeue

#435 fix: Return original result set invisibly from `dbBind()`
  R/dbBind_DBIResultArrow.R
Labels: mergequeue

#436 chore: `dbBind()` for `DBIResultArrow` passes `params` as is
  R/dbBind_DBIResultArrow.R
Labels: mergequeue

#415 feat: New `dbBindArrow()` to support passing nanoarrow streams for parameter binding
  NAMESPACE
  R/15-dbBind.R
  R/25-dbBindArrow.R
  R/dbBindArrow_DBIResult.R
  R/dbBindArrow_DBIResultArrowDefault.R
  man/dbBind.Rd
  man/dbClearResult.Rd
  man/dbColumnInfo.Rd
  man/dbFetch.Rd
  man/dbGetRowsAffected.Rd
  man/dbHasCompleted.Rd
  man/dbSendQuery.Rd
  man/dbSendStatement.Rd
  man/hidden_aliases.Rd
Labels: mergequeue

#440 CRAN release v1.2.0
  .github/workflows/install/action.yml
  DESCRIPTION
  NEWS.md
  R/deprecated.R
  README.Rmd
  README.md
  _pkgdown.yml
  cran-comments.md
  man/dot-SQL92Keywords.Rd
  revdep/.gitignore
  revdep/README.md
  revdep/cran.md
  revdep/failures.md
  revdep/problems.md
  vignettes/DBI-1.Rmd
  vignettes/DBI-proposal.Rmd
Labels: CRAN release :station:

#441 CRAN release v1.2.0
  DESCRIPTION
  R/00-Id.R
  cran-comments.md
  tests/testthat/test-00-Id.R
Labels: CRAN release :station:

#442 docs: use dbitemplate
  DESCRIPTION
  _pkgdown.yml
Labels: mergequeue

#445 feat: Use `nanoarrow::infer_nanoarrow_schema()` in the default method for `dbCreateTable()`
  R/dbCreateTableArrow_DBIConnection.R
Labels: mergequeue

#448 chore: Fix type inference in default method for `dbCreateTableArrow()`
  R/dbCreateTableArrow_DBIConnection.R
Labels: mergequeue

#450 chore: Fix type inference in default method for `dbCreateTableArrow()`
  R/dbCreateTableArrow_DBIConnection.R
  man/DBI-package.Rd
  man/dbAppendTable.Rd
  man/dbBind.Rd
  man/dbCreateTable.Rd
  man/dbDataType.Rd
  man/dbExistsTable.Rd
  man/dbFetch.Rd
  man/dbGetQuery.Rd
  man/dbGetStatement.Rd
  man/dbListObjects.Rd
  man/dbListTables.Rd
  man/dbReadTable.Rd
  man/dbRemoveTable.Rd
  man/dbUnquoteIdentifier.Rd
  man/dbWriteTable.Rd
Labels: mergequeue

#447 feat: Avoid coercing `params` in default implementation for `dbSendQueryArrow()`
  R/dbSendQueryArrow_DBIConnection.R
  vignettes/DBI-arrow.Rmd
Labels: mergequeue

#452 chore: Add badge to `DBIResultArrow` class
  R/07-DBIResultArrow.R
  man/DBIResultArrow-class.Rd
Labels: mergequeue

#453 feat: Add `temporary` argument to `dbCreateTableArrow()`
  R/22-dbCreateTableArrow.R
  R/sqlCreateTable.R
  man/dbCreateTable.Rd
  man/dbCreateTableArrow.Rd
  man/sqlCreateTable.Rd
Labels: mergequeue

#454 feat: `dbAppendTableArrow()` returns number of rows
  R/dbAppendTableArrow_DBIConnection.R
Labels: mergequeue

#451 docs: Finalize Arrow vignette
  DESCRIPTION
  tests/testthat/test-DBItest.R
  vignettes/DBI-arrow.Rmd
Labels: mergequeue
